### ISSUE TITLE
Penge Bitcoin

### ISSUE THREAD

**Issue by spencerjireh** [jcilacad/coin-monitor-hub#3]
pls

**Comment by jcilacad** [comment]
Need ko nga rin HAHAHA

**Comment by spencerjireh** [comment]
anong complete? di mo ako binigyan ng bitcoin. kahit isa lang ok na ako pre

**Comment by spencerjireh** [comment]
> Need ko nga rin HAHAHA

Di mo need. taas sahod sa oracle ahahahha

**Comment by jcilacad** [comment]
Kulit mo HAHAHA
